main:
	@echo "All examples contain it's own makefile and an be compiled separatly."
#	@echo "Call 'make all' to compile them all."
#	@echo ""

DIRS = $(wildcard */)

all:
	echo "Unimplemented, $(DIRS)"
